### ISSUE TITLE
write_csv_data() delete checking data_table_changed parameter

### ISSUE THREAD

**Issue by vladislabv** [VitaliKStud/video-labeler#12]
Hallo Vitali,

bin gerade am Schreiben des Usermanuals und habe an eine komische Sache gestoßen. Und zwar, die Funtion mit Ctrl+S wird nun dann aufgerufen, wenn ich mindestens eine Zeile lösche, sonst ist der Parameter `self.data_table_changed` ist False.

Das muss weg, da ich kein Problem sehe dem User an einem beliebigen Zeitpunkt die Möglichkeit zu geben, das Progress zu speichern, egal hat er grundsätzlich was geändert oder nicht.

**Comment by VitaliKStud** [comment]
Ich fix das, der parameter ist vor allem für autosave gedacht, falls die app mal bei jemanden abstürzt, dass man keinen riesen Datenverlust erleidet. Ich werde den Parameter kurz davor auf True dann auf False wieder nach dem speichern
