### ISSUE TITLE
Play / Progress Bar of the Video Player is buggy

### ISSUE THREAD

**Issue by vladislabv** [VitaliKStud/video-labeler#3]
Hey Vitali,

ich habe es mir etwas getestet, und erstmal positives, wir brauchen soweit ich verstehe explizit kein MPV Player mehr. Sehr schön! Wie hast du das hinbekommen?

Zum Bug:

wenn ich mir ein .mp4 Video angucke, startet es halt normal, wenn über die Hälfte der Videolänge bin und möchte mir nun zum Anfang springen, geht es über den Progress Bar gar nicht.

Also wenn ich klicke auf eine Position die hinter dem Playpunkt liegt, springt es kurz dorthin und wiederzurück, so dass ich nach vorne ein Video abspielen lassen kann.

**Comment by VitaliKStud** [comment]
MPV player ist in der hinsicht nicht dringend notwendig, jedoch ist der mit seiner Schnittstelle relativ gut. Würde den in dem Fall auch behalten. Weil da kann man die Geschwindigkeit des Videos etc. auch per Hotkeys (definierte Hotkeys) z.B. vberlangsamen.

Probierst dus auf Linux aus? Hatte bei mir alles auf Windows getestet. Wie lang sind die Videos?

**Comment by VitaliKStud** [comment]
Videos were corrupted. No fix needed
